### PR TITLE
Implemented shortener 0.1.0.0

### PR DESCRIPTION
**Pull request by dedifferentiator**

### CODE REVIEW

**Comment by dedifferentiator** [comment]
image

**Review by p3rsik — APPROVED** [review]
You're the best!11! Around... Nothing’s gonna ever keep you down!111!!

**Comment by dedifferentiator** [comment]
@p3rsik no uuuu!!!!1!!1!11!

**Comment by dedifferentiator** [comment]
@p3rsik gg;wp

**Pull request merged**
